services:
  - type: web
    name: space-runner-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: true
      - key: WEBAPP_URL
        fromSecret: true
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 8080